import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'public/v3/css/style.css',
                'public/v3/css/html-sitemap.css',
                'resources/css/blog/category.css',
                'resources/css/company/companies.css',
                'resources/css/company/company.css',
                'resources/css/company/companies-main-content.css',
                'resources/css/company/company-catalog-item.css',
                'resources/css/company/company-catalog-section.css',
                'resources/css/company/company-review.css',
                'resources/css/company/company-review-add.css',
                'resources/css/company/company-reviews.css',
                'resources/css/company/company-reviews-main.css',
                'resources/css/courses/course.css',
                'resources/css/courses/course-card.css',
                'resources/css/courses/courses-cards.css',
                'resources/css/courses/courses-main.css',
                'resources/css/employee/employee.css',
                'resources/css/header/header.css',
                'resources/css/listing/listing.css',
                'resources/css/listing/rating_stars.css',
                'resources/css/mainpage/mainpage.css',
                'resources/css/mainpage/mainpage-categories.css',
                'resources/css/mainpage/mainpage-category-item.css',
                'resources/css/mainpage/mainpage-head.css',
                'resources/css/mainpage/mainpage-news.css',
                'resources/css/mainpage/mainpage-posts.css',
                'resources/css/post/post.css',
                'resources/css/post/post-card.css',
                'resources/css/employee/employee-info.css',
                'resources/css/history/history.css',
                'resources/css/pagination/pagination.css',
                'resources/css/search/search-courses.css',
                'resources/css/mainpage/mainpage-reviews.css',
                'resources/css/auth/auth.css',
                'resources/css/auth/register.css',
                'resources/css/sitemap/sitemap-listing.css',
                'resources/css/sitemap/sitemap-companies.css',
                'resources/css/not-found/not-found.css',
                'resources/js/company/companies.js',
                'resources/js/company/company-review.js',
                'resources/js/company/company-review-add.js',
                'resources/js/company/company-reviews.js',
                'resources/js/courses/courses-cards.js',
                'resources/js/header/header.js',
                'resources/js/listing/listing.js',
                'resources/js/listing/rating_stars.js',
                'resources/js/ratings/rating_stars_simple.js',
                'resources/js/news/news.js',
            ],
            refresh: true,
        }),
    ],
});
